
# Load Libraries 
```{r, message=FALSE}
library(tidyverse)
library(gt)
library(janitor)
library(ghibli)
```

# Load Data
```{r}
tuesdata <- tidytuesdayR::tt_load('2024-12-03')
traffic <- tuesdata$A64_traffic
```

```{r}
traffic_clean <- traffic %>% clean_names() %>% 
  select(-site_id, -site_name, -report_date, -time_period_ending, -time_interval,
         -name, -longitude, -latitude) %>% 
  rename(`0-520` = x0_520_cm,
         `521-660` = x521_660_cm,
         `661-1160` = x661_1160_cm,
         `Over 1160` = x1160_cm) %>% 
  pivot_longer(cols = `0-520`:`Over 1160`,
               names_to = "size_class_cm",
               values_to = "num_by_size") %>% 
  pivot_longer(cols = x0_10_mph:x80_mph,
               names_to = "speed_cat_mph",
               values_to = "num_by_speed") %>% 
  mutate(speed_cat_mph = str_replace(speed_cat_mph, "x", ""),
         speed_cat_mph = str_replace(speed_cat_mph, "_mph", ""),
         speed_cat_mph = str_replace(speed_cat_mph, "_", "-"), 
         speed_cat_mph = ifelse(speed_cat_mph == "80", "Over 80", speed_cat_mph),
         size_class_cm = as.factor(size_class_cm)) 
```

```{r}
traffic_clean %>% 
  ggplot(aes(x= size_class_cm, y= num_by_size, fill = size_class_cm))+
  geom_boxplot() +
  labs(title = "Distribution of vehicules by size class",
       x = "Size Classes (cm)",
       y = "Number of Vehicles") +
  theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        legend.position = "none",
        panel.background = element_rect(fill = "azure1"))+
  #custom the colors 
  scale_fill_ghibli_d("MarnieMedium1", direction =-1)
```
```{r}
traffic_clean %>% 
  group_by(size_class_cm) %>% 
  summarize(avg_by_size = mean(num_by_size, na.rm = T)) %>% 
  ggplot(aes(x= size_class_cm, y= avg_by_size))+
  geom_bar(stat="identity")+
   labs(title = "Distribution of vehicules by speeding category",
       x = "Speed Categories",
       y = "Number of Vehicles") +
  theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        legend.position = "none",
        panel.background = element_rect(fill = "azure1"))
```

```{r}
traffic_clean %>% group_by(speed_cat_mph) %>% 
  summarize(avg_by_speed = mean(num_by_speed, na.rm = T)) %>% 
  ggplot(aes(x= speed_cat_mph, y= avg_by_speed, fill = speed_cat_mph))+
  geom_bar(stat= "identity")+
  labs(title = "Distribution of vehicules by speeding category",
       x = "Speed Categories",
       y = "Average Number of Vehicles") +
  theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 30, vjust = 0.8, hjust=0.5),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        legend.position = "none",
        panel.background = element_rect(fill = "azure1"))
```




